### ISSUE TITLE
fix broken link image

### ISSUE THREAD

**Issue by Saz5359** [Saz5359/MyfirstWebsite#1]
The first image on the carousal is not loading which is due to a broken link which needs to be replaced

**Comment by CodingOdysseyOrginal** [comment]
Hi, i think the issue is that the picture is linked to a website(copyright issue?) and that you'll need to the screenshot the image and save it to your image files and link it from there.

**Comment by Saz5359** [comment]
PR#2 broken link image fixed and closed
